---
- name: Create namespace
  community.okd.k8s:
    api_version: v1
    kind: Namespace
    name: process-test

- name: Process a template in the cluster
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift # only needed if using a template already on the server
    parameters:
      NAMESPACE: openshift
      NAME: test123
  register: result

- name: Create the rendered resources
  community.okd.k8s:
    namespace: process-test
    definition: '{{ item }}'
    wait: yes
    apply: yes
  loop: '{{ result.resources }}'

- name: Delete the rendered resources
  community.okd.k8s:
    namespace: process-test
    definition: '{{ item }}'
    wait: yes
    state: absent
  loop: '{{ result.resources }}'


- name: Process a template and create the resources in the cluster
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift # only needed if using a template already on the server
    parameters:
      NAMESPACE: openshift
      NAME: test123
    state: present
    namespace_target: process-test
  register: result

- name: Process a template and update the resources in the cluster
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift # only needed if using a template already on the server
    parameters:
      NAMESPACE: openshift
      NAME: test123
      MEMORY_LIMIT: 1Gi
    state: present
    namespace_target: process-test
  register: result

- name: Process a template and delete the resources in the cluster
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift # only needed if using a template already on the server
    parameters:
      NAMESPACE: openshift
      NAME: test123
    state: absent
    namespace_target: process-test
  register: result

- name: Process a template with parameters from an env file and create the resources
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift
    namespace_target: process-test
    parameter_file: '{{ files_dir }}/nginx.env'
    state: present
    wait: yes

- name: Process a template with parameters from an env file and delete the resources
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift
    namespace_target: process-test
    parameter_file: '{{ files_dir }}/nginx.env'
    state: absent
    wait: yes


- name: Process a template with duplicate values
  community.okd.openshift_process:
    name: nginx-example
    namespace: openshift # only needed if using a template already on the server
    parameters:
      NAME: test123
    parameter_file: '{{ files_dir }}/nginx.env'
  ignore_errors: yes
  register: result

- name: Assert the expected failure occurred
  assert:
    that:
      - result.msg is defined
      - result.msg == "Duplicate value for 'NAME' detected in parameter file"
