---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: '{{ virtualenv_interpreter }}'
  tasks:
    # OpenShift Resources
    - name: Create a project
      community.okd.k8s:
        name: testing
        kind: Project
        api_version: project.openshift.io/v1
        apply: no
      register: output

    - name: show output
      debug:
        var: output

    - name: Create deployment config
      community.okd.k8s:
        state: present
        inline: &dc
          apiVersion: v1
          kind: DeploymentConfig
          metadata:
            name: elastic
            labels:
              app: galaxy
              service: elastic
            namespace: testing
          spec:
            template:
              metadata:
                labels:
                  app: galaxy
                  service: elastic
              spec:
                containers:
                  - name: elastic
                    volumeMounts:
                      - mountPath: /usr/share/elasticsearch/data
                        name: elastic-volume
                    command: ['elasticsearch']
                    image: 'ansible/galaxy-elasticsearch:2.4.6'
                volumes:
                  - name: elastic-volume
                    persistentVolumeClaim:
                      claimName: elastic-volume
            replicas: 1
            strategy:
              type: Rolling
      register: output

    - name: Show output
      debug:
        var: output
