---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: '{{ virtualenv_interpreter }}'

  tasks:

    - pip:
        name: kubernetes-validate==1.12.0
        virtualenv: "{{ virtualenv }}"
        virtualenv_command: "{{ virtualenv_command }}"
        virtualenv_site_packages: no

    - import_tasks: tasks/validate_installed.yml

    - pip:
        name: kubernetes-validate
        state: absent
        virtualenv: "{{ virtualenv }}"
        virtualenv_command: "{{ virtualenv_command }}"
        virtualenv_site_packages: no

    - import_tasks: tasks/validate_not_installed.yml
