---
- include_tasks: setup_remote_tmp_dir.yml

- set_fact:
    virtualenv: "{{ remote_tmp_dir }}/virtualenv"
    virtualenv_command: "{{ ansible_python_interpreter }} -m virtualenv"

- set_fact:
    virtualenv_interpreter: "{{ virtualenv }}/bin/python"

- pip:
    name: virtualenv

# Test openshift

- debug:
    var: k8s_openshift

- pip:
    name:
      - kubernetes-validate==1.12.0
      - openshift>=0.9.2
      - coverage
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "{{ virtualenv_command }}"
    virtualenv_site_packages: no

- include_tasks: openshift.yml
  when: k8s_openshift | bool
